### ISSUE TITLE
not support cmd

### ISSUE THREAD

**Issue by yangxin520520** [go-cmd/cmd#101]
findCmd := cmd.NewCmd("cjpeg", "-quality", "80", "public/a22_9.jpg>/public/a22.jpg")

[-quality 80 public/a22_9.jpg>/public/a22.jpg] -----------------findCmd.Stderr
-------------------------no
{jpegtran 276818 true 1 <nil> 1699908153802181801 1699908153802675350 0.000493549 [] [usage: jpegtran [switches] [inputfile] Switches (names may be abbreviated):   -copy none     Copy no extra markers from source file   -copy comments Copy only comment markers (default)   -copy icc      Copy only ICC profile markers   -copy all      Copy all extra markers   -optimize      Optimize Huffman table (smaller file, but slow compression, enabled by default)   -progressive   Create progressive JPEG file (enabled by default)   -revert        Revert to standard defaults (instead of mozjpeg defaults)   -fastcrush     Disable progressive scan optimization Switches for modifying the image:   -crop WxH+X+Y  Crop to a rectangular region   -drop +X+Y filename          Drop (insert) another image   -flip [horizontal|vertical]  Mirror image (left-right or top-bottom)   -grayscale     Reduce to grayscale (omit color data)   -perfect       Fail if there is non-transformable edge blocks   -rotate [90|180|270]         Rotate image (degrees clockwise)   -transpose     Transpose image   -transverse    Transverse transpose image   -trim          Drop non-transformable edge blocks                  with -drop: Requantize drop file to match source file   -wipe WxH+X+Y  Wipe (gray out) a rectangular region Switches for advanced users:   -icc FILE      Embed ICC profile contained in FILE   -restart N     Set restart interval in rows, or in blocks with B   -maxmemory N   Maximum memory to use (in kbytes)   -maxscans N    Maximum number of scans to allow in input file   -outfile name  Specify name for output file   -report        Report transformation progress   -strict        Treat all warnings as fatal   -verbose  or  -debug   Emit debug output   -version       Print version information and exit Switches for wizards:   -scans FILE    Create multi-scan JPEG per script FILE]}

**Comment by daniel-nichter** [comment]
`"public/a22_9.jpg>/public/a22.jpg"` won't work as an argument because of the `>` redirection. You need to set [Cmd.Stdout](https://pkg.go.dev/github.com/go-cmd/cmd#Cmd) (or other related options) to redirect stdout output.
