### ISSUE TITLE
special character '>'

### ISSUE THREAD

**Issue by 2013kaa** [go-cmd/cmd#102]
Hello
I have a command to build gradle like: ./gradlew build final dependencies > dep.txt

but when executed through cmd.NewCmdOptions it gives an error when building in the Gradle: Task '>' not found in root project 'xxxx'.

tell me how to solve the problem?there may be some kind of special character escaping >

**Comment by daniel-nichter** [comment]
`>` is output redirection, not part of the command. So use [Options](https://pkg.go.dev/github.com/go-cmd/cmd#Options) to set streaming or buffered output (and to combine STDOUT or STDERR or not). If you choose streaming output, you'd read [Cmd.Stdout](https://pkg.go.dev/github.com/go-cmd/cmd#Cmd) (and/or .Stderr) channels and write them to a file. If you choose buffered output, you'd copy [Status.Stdout](https://pkg.go.dev/github.com/go-cmd/cmd#Status) (and/or .Stderr) to file.
