### ISSUE TITLE
How to hide the console window?

### ISSUE THREAD

**Issue by isensen** [go-cmd/cmd#103]
Hello, when using exec.Command, you can use the following code to hide the console window, may I ask how go-cmd achieve the same effect?
```
taskCmd := exec.Command("cmd", "/c", "tasklist")
taskCmd .SysProcAttr = &syscall.SysProcAttr{HideWindow: true}
```

**Comment by xmapst** [comment]
> Hello, when using exec.Command, you can use the following code to hide the console window, may I ask how go-cmd achieve the same effect?
> 
> ```
> taskCmd := exec.Command("cmd", "/c", "tasklist")
> taskCmd .SysProcAttr = &syscall.SysProcAttr{HideWindow: true}
> ```

```golang
	cmd.Options{
		// ......
		BeforeExec: []func(cmd *exec.Cmd){
			func(cmd *exec.Cmd) {
				cmd.SysProcAttr = &syscall.SysProcAttr{
					HideWindow:    true,
				}
			},
		},
	}
```

**Comment by isensen** [comment]
> > Hello, when using exec.Command, you can use the following code to hide the console window, may I ask how go-cmd achieve the same effect?
> > ```
> > taskCmd := exec.Command("cmd", "/c", "tasklist")
> > taskCmd .SysProcAttr = &syscall.SysProcAttr{HideWindow: true}
> > ```
> 
> ```go
> 	cmd.Options{
> 		// ......
> 		BeforeExec: []func(cmd *exec.Cmd){
> 			func(cmd *exec.Cmd) {
> 				cmd.SysProcAttr = &syscall.SysProcAttr{
> 					HideWindow:    true,
> 				}
> 			},
> 		},
> 	}
> ```

Thank you
