### ISSUE TITLE
Compile error on windows

### ISSUE THREAD

**Issue by xmxiaoq** [go-cmd/cmd#12]
.\cmd.go:192:9: undefined: syscall.Kill
.\cmd.go:244:48: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr

**Comment by daniel-nichter** [comment]
Sorry, this pkg doesn't work on Windows and there are no plans to support Windows. (Duplicate of issues #2 and #5)

**Comment by daniel-nichter** [comment]
Windows should work as of v1.1.0.
