### ISSUE TITLE
Race condition on short Timeout

### ISSUE THREAD

**Issue by davrux** [go-cmd/cmd#16]
There is a race condition if you try to stop the process after a short timeout. I think the problem, is that c.run() is called in an own go routine:

    go c.run()
    return c.statusChan

The example program may call Stop before the process even started and returns nil. The external program is not killed. One solution would be to select on status and check started before defining any timeout.

    package main
    
    import (
    	"fmt"
    	"time"
    
    	"github.com/go-cmd/cmd"
    )
    
    func main() {
    	// Start a long-running process, capture stdout and stderr
    	findCmd := cmd.NewCmd("find", "/")
    	statusChan := findCmd.Start() // non-blocking
    
    	ticker := time.NewTicker(2 * time.Second)
    
    	// Print last line of stdout every 2s
    	go func() {
    		for range ticker.C {
    			status := findCmd.Status()
    			n := len(status.Stdout)
    			fmt.Println(status.Stdout[n-1])
    		}
    	}()
    
    	// Stop command after short time.
    	go func() {
    		<-time.After(1 * time.Millisecond)
    		fmt.Printf("Timeout reached.")
    		findCmd.Stop()
    	}()
    
    	// Block waiting for command to exit, be stopped, or be killed
    	finalStatus := <-statusChan
    	fmt.Printf("%+v", finalStatus)
    }

**Comment by daniel-nichter** [comment]
Thanks for the report. I think the issue is that, in this case, Stop returning nil is misleading because of this block:
```go
    // Nothing to stop if Start hasn't been called, or the proc hasn't started,
    // or it's already done.
    if c.statusChan == nil || !c.started || c.done {
        return nil
    }
```
If the cmd hasn't started yet, Stop returns nil which gives the impression that it was stopped ok when really it hadn't even started yet. So I don't think there's a race condition per-se, but rather that Stop should return an error, perhaps ErrNotRunning. In that case, caller knows that they need to wait and try again.

**Comment by davrux** [comment]
Yes, i think that would help. So it's easy to come back laster if the function returns ErrNotRunning.

**Comment by daniel-nichter** [comment]
Well it took a _very_ long time, but finally fixed: https://github.com/go-cmd/cmd/pull/52
