### ISSUE TITLE
add windows support

### ISSUE THREAD

**Issue by rizkyramadhan** [go-cmd/cmd#18]
Please, please add windows support..  currently when i use it in window, it throws: 

```
D:\Go\src\github.com\go-cmd\cmd\cmd.go:204:9: undefined: syscall.Kill
D:\Go\src\github.com\go-cmd\cmd\cmd.go:279:48: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr
```

**Comment by daniel-nichter** [comment]
Sorry, no plans to support Windows (re issue #2, #5, and #12). This code use low-level Unix-specific code, so it's not clear how it would work for Windows (and Windows programming is not my expertise).

**Comment by daniel-nichter** [comment]
Windows should work as of v1.1.0.

**Comment by rizkyramadhan** [comment]
:heart_eyes:
