### ISSUE TITLE
Stdout empty when line is 65k or more

### ISSUE THREAD

**Issue by its-johnt** [go-cmd/cmd#30]
Hi, thank you for writing this package. I'm using it to run a command that outputs a long JSON string all on one line. I discovered that when the output reaches 2^16 chars on a line the Stdout is empty. An example program is below:

```
package main

import ( 
    "fmt"
    "log"

    "github.com/go-cmd/cmd"
)

func main() { 
    for i := 65534; i < 65540; i++ {
        bashScript := fmt.Sprintf("for i in {1..%d} ; do echo -n X ; done", i)
        c := cmd.NewCmd("/bin/bash", "-c", bashScript)
        s := <-c.Start()
        if s.Error != nil {
            log.Fatal(s.Error)
        }
        fmt.Printf("%d output chars - %d Stdout lines\n", i, len(s.Stdout))
    } 
}
```

My output (on `go version go1.11.5 linux/amd64`) is:
```
65534 output chars - 1 Stdout lines
65535 output chars - 1 Stdout lines
65536 output chars - 0 Stdout lines
65537 output chars - 0 Stdout lines
65538 output chars - 0 Stdout lines
65539 output chars - 0 Stdout lines
```

If you need any more info from me please let me know. Thanks much.

**Comment by renard** [comment]
This is a hard limit set in most kernels.
See: https://unix.stackexchange.com/questions/11946/how-big-is-the-pipe-buffer#answer-11954

**Comment by daniel-nichter** [comment]
That's interesting, but as renard mentioned: looks like a kernel limitation. That being the case, there's no easy fix that I can think of off hand, so I'll close this issue. But if more people run into this, give a 👍  on the original post and we can look into it more.

One workaround might be: compress with [gzip](https://golang.org/pkg/compress/gzip/) before sending.
