### ISSUE TITLE
Maintaining the project

### ISSUE THREAD

**Issue by croqaz** [go-cmd/cmd#33]
Hi @daniel-nichter , I would like to maintain this project, if you agree.

This is the initial list of things I would like to do:

* keep the test coverage above 95% or 100% if possible
* simplify the tests by using a more advanced testing library?
* implement a Clone function to duplicate a Cmd to be able to start it again, fresh
* implement sending signals to the Cmd
* implement a consistent state of the Cmd, instead of multiple variables (started, stopped, final, etc)
* implement watching the state changes via channels
* more love to the readme file
* find a nice logo? :) 
* support only the *3* most recent Go-lang versions (ex: currently 1.12, 1.11 and 1.10)
* I understand there are projects using this lib, so I'll work on a separate development branch and create tags for every major change

I am building a process manager on top of this project and that project is used in another project so it's in my best interest to have this lib stable and up to date.
You can see some of the changes I mentioned above in here: https://github.com/ShinyTrinkets/overseer but I'll take a safer approach with this lib.

**Comment by daniel-nichter** [comment]
Hi Cristi,

That sounds good. I have some feedback from others who’ve used the package. I’m mostly away this week, but will get back to you as soon as possible. You can email me directly at nil@codenode.com. In the meantime, I’ll add you to the Github org.

-Daniel

**Comment by croqaz** [comment]
Hi ! Thank you !
There's no emergency, we can talk once you're back.
Most of the stuff that I mentioned is already implemented on my repo.
Why I wanted to contribute was to give back, because there might be people that are using this, as you said. Also I want to challange myself to maintain a repo that is not created by me :)

**Comment by croqaz** [comment]
Closing this, because it's not needed.
