### ISSUE TITLE
New release after go.mod changes

### ISSUE THREAD

**Issue by akkumar** [go-cmd/cmd#38]
Thanks for accepting PR #37 . 

As a logical extension to the same, it would be useful to have a 1.0.6 or a 1.1.0 release as you see appropriate. This makes projects dependent on go-cmd have a more readable go.mod as opposed to yyyymmdd-hash kind of version in their projects.

**Comment by daniel-nichter** [comment]
Sorry for slow reply. Right, meant to push a new version but forgot. Just pushed it: v1.0.6
