### ISSUE TITLE
Long running commands with a lot of output

### ISSUE THREAD

**Issue by telemac** [go-cmd/cmd#4]
Hi,
Is there a way to avoid the output accumulation in the string arrays, and get the output data in real time in a channel, or with a callback ?

For instance to handle a long running tail -f on a fast growing file.

Thank you for the great work.

**Comment by anshap1719** [comment]
Here's a little hack I used to achieve what you are looking for. Please note that I am new to programming and don't know if my solution is resource heavy, if you do have knowledge about this, let me know.

```
ticker := time.NewTicker(time.Nanosecond)

var previousLine string

go func() {
	for range ticker.C {
		status := c.Status()
		n := len(status.Stdout)
		if n < 1 {
			continue
		}
		currentLine := status.Stdout[n - 1]
		if previousLine != currentLine || previousLine == "" {
			fmt.Println(status.Stdout[n - 1])
			previousLine = currentLine
		} else {
			continue
		}
	}
}()
```

**Comment by daniel-nichter** [comment]
Hi. Sorry for super slow reply. My day job keeps me very busy, day and night. :-)

@anshap1719 Your solution would work but is, imho, not the optimal approach because it's polling, and polling is usually problematic, doesn't scale, etc. (Polling is correct/best solution in specific cases, just not this case.)

Presuming, @telemac, that you want a true streaming solution (more akin to a push model than pull/polling model), the best solution would be a variation of this pkg that has the internal `output` object (which implements `io.Writer` interface) push the lines to a channel as they come in via the cmd's calls to `Write`.

I've never tried that, but I'll give it a try. No promises if it'll work or when I could write something complete, correct (i.e. no race conditions), and tested.

**Comment by daniel-nichter** [comment]
Turns out this is possible and not too difficult. I have a PR open. It works but I need to handle a buffer overrun and then it should be good to go.

**Comment by anshap1719** [comment]
@daniel-nichter Will it be possible for you to provide sample code for the streaming output as well?

Thanks.

**Comment by mraaroncruz** [comment]
This issue is two parts:
- how can we not get a build up in the private slices, so avoiding memory leaks ([these ones](https://github.com/go-cmd/cmd/pull/8/commits/279d85612c5e0eaa923d02b1c209c4850470a5cb#diff-0cf3d18277fde705f1a4eb69fddfefc1R28))
- how to stream the output to a channel or something

The two solutions (@anshap1719's solution and @daniel-nichter's PR) focus on the second while ignoring the first, which was my main concern.

Maybe this should be two different issues (or maybe it is already)?

**Comment by daniel-nichter** [comment]
I think latest master solves this. See [docs](https://godoc.org/github.com/go-cmd/cmd) and an [example](https://github.com/go-cmd/cmd/blob/master/examples/blocking-streaming/main.go).

@mraaroncruz Buffered output will hold memory until the code causes the reference count to the Cmd to drop to zero. If this isn't the case, please file a bug. But with latest master, one can simply disable buffered output altogether, and do streaming only. Granted, the stream has an internal 8k buffer, so strictly speaking the code needs to drop all refs to the Cmd, too, if it wants to free that buffer.

**Comment by telemac** [comment]
I'll give it a try soon, thank you sharing your work.

**Comment by anshap1719** [comment]
@daniel-nichter Works really well. Thanks for this.

**Comment by anshap1719** [comment]
@daniel-nichter Works really well. Thanks for this.

**Comment by mraaroncruz** [comment]
@daniel-nichter Thanks for your explanation.

What I understood from reading the code and from the examples is that, in a long running command, there is an [internal buffer](https://github.com/go-cmd/cmd/blob/master/cmd.go#L68) that is forever appended to that is impossible to access, limit, or clear.

[Buffers released on done](https://github.com/go-cmd/cmd/blob/master/cmd.go#L211-L212)

[Buffers not released when not done](https://github.com/go-cmd/cmd/blob/master/cmd.go#L216-L223)

Maybe I'm missing something (or it has changed). But when I was looking to use this project on something that would collect output "forever" to parse, I couldn't find a way to release these buffers without changing the implementation.

It sounds like if I wanted to use the library now, streaming would be perfect with the 8k buffer you mentioned above. I look forward to needing this tool again.

**Comment by jshort** [comment]
Along these lines, I’ve noticed that the sample in the readme doesn’t really work in that the Status’ stdout is always empty until the find command finishes. This is assuming you put the check for n > 1 in the ticker go routine.

**Comment by mstave** [comment]
With latest code as of now,  with a shell `find` command that takes awhile and produces a good amount of output - it works in blocking mode, but with streaming mode it prints some subset of the output, or hangs, or generates a hidden broken pipe error, or some combination of the above.  Changing `STREAM_BUFFER_SIZE` and/or `STREAM_CHANNEL_SIZE` seems to help some, but even if my `Stdout`/`Stderr` readers do nothing with the data, it takes a ~80 seconds to run, vs 
```bash
11:41 $ time find ~/temp | wc
  104712  106430 12110522

real    0m1.166s
user    0m0.246s
sys     0m0.958s
```

100K lines + 12MB data is fairly large for a shell command, but it's unclear the amount of data with which it can be reliable.  

Is this to be expected?

The streaming stuff is cool if it works, in non-streaming mode, is there an advantage to using this vs. 

```golfing
shCmd := exec.Command(...)
out, err := shCmd.Output()
```
?

Thanks for writing this stuff, and making it available!

**Comment by daniel-nichter** [comment]
@mstave It's possible the streaming code isn't optimal enough yet; it's a first (or second) quick attempt. I'll try it with more significant output and see if I can reproduce this...

**Comment by daniel-nichter** [comment]
That was easy: a lot of output overwhelms the buffer and breaks the pipe. Indeed, this simple implementation doesn't scale to handle a lot of output very quickly... Works fine for less/slower output, but I'll see what I can do to improve it for the former. My time is pretty limited, so if anyone has any ready-made streaming string parsing algos/loops that I can just drop into `func (rw *OutputStream) Write(p []byte) (n int, err error)`, that'd be nice. :-)

**Comment by daniel-nichter** [comment]
Actually, that's not the true root cause, but I know what is. I think I might have a much better, simpler, and faster way to implement this...

**Comment by daniel-nichter** [comment]
@mstave Latest commit c640b65 fixes/improves streaming output. In my local tests it worked as expected with a lot of fast output. Let me know how it works for you. This rev is also a lot more efficient, so it shouldn't be noticeably slower, either.

**Comment by mstave** [comment]
@daniel-nichter Thanks!  I'll take a look

**Comment by daniel-nichter** [comment]
Had a chance to take a look?

**Comment by mstave** [comment]
@daniel-nichter Fixed!  Well played.  Thanks.

**Comment by daniel-nichter** [comment]
Excellent, thanks!
