### ISSUE TITLE
not work on windows

### ISSUE THREAD

**Issue by trumpliu2018** [go-cmd/cmd#40]
.\api-service-platform-master-fbddfc271a9e5a3d8ac1e03ac6305e24a7325521\pkg\mod\github.com\go-cmd\cmd@v1.0.5\cmd.go:298:41: unknown field 'Setpgid' in struct literal of type syscall.SysP
rocAttr

**Comment by daniel-nichter** [comment]
> cmd@v1.0.5
You need to update to v1.1.0.
