### ISSUE TITLE
Process not being killed

### ISSUE THREAD

**Issue by absolutejam** [go-cmd/cmd#42]
I'm working on wrapping `cloudflared` with a HTTP interface, but I'm experiencing issues wherein the command isn't being killed and my application is hanging trying to read from the 'done' channel (`<-command.Done()`).

Amongst other bits, I have a function along the following lines that is called when I attempt to 'close' a tunnel:

```go
func stopTunnel(tun *tunnelCmd) {
	log.Infof("Stopping tunnel for %s", tun.Hostname)

	var complete = tun.Command.Status().Complete
	if !complete {
		if err := tun.Command.Stop(); err != nil {
			log.Error(err)
		}

		// Added for debugging
		log.Warn("Waiting for Done()")
		go func() {
			for {
				time.Sleep(2 * time.Second)
				log.Infof("-- %+v", tun.Command.Status())
			}
		}()
		// end

		<-tun.Command.Done()
		log.Infof("Existing tunnel for %s stopped with code %d", tun.Hostname, tun.Command.Status().Exit)
	}

	log.Infof("Stopped tunnel for %s", tun.Hostname)
}
```

In the above example, I've added in a goroutine to poll, so I can observe the state of the `Command` and I can see that it's still running. If I manually `pkill -9 <pid>` it will unblock the `Done` channel and all is as expected.

I'm looking at possibly forking and adding some logging because I'm not sure what's causing this issue, but I'm also concerned that perhaps the actual SIGTERM needs to be better enforced? Any ideas off that bat?

Thanks for your work on this library!

**Comment by daniel-nichter** [comment]
If `kill -9` works but a normal stop doesn't, then the program isn't responding (or responding very close) to a normal stop/kill. The `Cmd.Done` chan is closed on `defer`, so nothing should stop that from happening and unblocking `<-tun.Command.Done()`.

I'd check the original process logs and make sure it's actually terminating. Also make sure process didn't work and start a new process group (pg), in which case killing the original pg won't kill the new, standalone process.

If you can reproduce this, please let me know. Will close this issue for now.
