### ISSUE TITLE
Mixed output

### ISSUE THREAD

**Issue by renard** [go-cmd/cmd#47]
I took the code from `examples/blocking-streaming` and replaced the `print-some-lines` with something that prints (and flushes) 0 to 9 randomly to stdout or stderr:

```python
#!/usr/bin/env python3

import sys
import time
import random

for i in range(10):
    r = random.random()
    if r > 0.5:
        sys.stdout.write("o: %d\n" % i)
        sys.stdout.flush()
    else:
        sys.stderr.write("e: %d\n" % i)
        sys.stderr.flush()
    time.sleep(0.000035)
```
One example can be:
```
e: 0
e: 1
o: 2
o: 3
e: 4
o: 5
e: 6
e: 7
o: 8
e: 9
```
Numbers should always be in order but the output channel (`o` or `e`) can change.

I ran the following test (It grabs the numbers, computes the md5sum, and see if there are any diverting results):

```shell
for i in $(seq 100); do ./cmd-test . 2>&1| awk '{print $2}'| md5; done | sort | uniq -c
```
The expected output is:
```
 100 e20b902b49a98b1a05ed62804c757f94
```

If the sleep time is too low (0.000035 something on my computer) I start to get some weird results such as:
```
   2 6d0cfa70985c6d01424ec5c2cfb50c4d
  98 e20b902b49a98b1a05ed62804c757f94
```
Meaning a mix in result lines. I start to get:
```
e: 0
e: 2
e: 4
o: 1
o: 3
o: 6
o: 9
e: 5
e: 7
e: 8
```

Did I missed something? How can I manage to get lines in correct order?

(I can provide further details if needed)

Thanks in advance.

**Comment by daniel-nichter** [comment]
The problem should be due to randomness of `select`:
```go
            select {
            case line, open := <-envCmd.Stdout:
                if !open {
                    envCmd.Stdout = nil
                    continue
                }
                fmt.Println(line)
            case line, open := <-envCmd.Stderr:
                if !open {
                    envCmd.Stderr = nil
                    continue
                }
                fmt.Fprintln(os.Stderr, line)
            }
```
Go does not guarantee which of those two chans will unblock first. So if the sleep in the Python code is super low, it's basically a `select` race condition. I think this can be proven with a 1s sleep (or even just 200ms probably): if the output is always correct, then we know it's just `select` randomness.

**Comment by renard** [comment]
Thanks for the feedback. Indeed this is the reason why.

Since this is not go-cmd related I guess we can close the issue.
