### ISSUE TITLE
go get does not work on Windows

### ISSUE THREAD

**Issue by simonjcarr** [go-cmd/cmd#5]
Windows 10

When I type  go get github.com/go-cmd/cmd

I get the following error

# github.com/go-cmd/cmd
go\src\github.com\go-cmd\cmd\cmd.go:123:9: undefined: syscall.Kill
go\src\github.com\go-cmd\cmd\cmd.go:173:48: unknown field 'Setpgid' in struct literal of type syscall.SysProcAttr

**Comment by daniel-nichter** [comment]
Sorry, this package only works on Linux. I never use Windows, so there's no plans to port or make this package compatible with Windows.

**Comment by daniel-nichter** [comment]
See #2

**Comment by daniel-nichter** [comment]
Windows should work as of v1.1.0.
