### ISSUE TITLE
how to change the bufSize of the stdoutStream when i use cmd.NewCmdOptions.. to get the object?

### ISSUE THREAD

**Issue by ChessC95** [go-cmd/cmd#66]
hello , my question is :
when i use the following code `envCmd := cmd.NewCmdOptions(cmdOptions, args[0], args[1:]...)` to get the envCmd object, can i still change the value of stdoutStream's bufSize in the envCmd object ?
it confused me a lot . thanks !

**Comment by bjohnsonAPF** [comment]
I have run into the same issue. If you create a `Cmd` object using `NewCmdOptions` or `NewCmd` the `NewOutputStream` is created for you with the default `bufSize`. The `stdoutStream` field of `Cmd` is not public so you can not use it to set a new `bufSize` with the `SetLineBufferSize` function.

**Comment by Crevil** [comment]
I'd love to make a PR on this to make the line buffer size configurable if that would be accepted. 🙏 

We have hit this issue in the past migrating off of `go-cmd` but I'd much rather add it here as it seems more users could benifit from it. 🙏  @daniel-nichter would you accept a PR on this? If not no problem ofc, I just don't want to spend the time creating a PR if in vain 😄

**Comment by daniel-nichter** [comment]
@Crevil  That'd be a good PR. I think the original hard-coded value predate [Options](https://pkg.go.dev/github.com/go-cmd/cmd#Options), but these can be options now.

**Comment by daniel-nichter** [comment]
Released as v1.4.1.
