### ISSUE TITLE
Is there a way to have stderr buffered into stdout

### ISSUE THREAD

**Issue by jwomackgsa** [go-cmd/cmd#70]
I know the standard os/exec lib has a function called CombinedOutput.  Can go-cmd do something similar?  My use case is after an executable has run, I am writing the stdout / stderr buffers to a log file.  If the executable's output produces both stdout and stderr output, I don't have a way to produce a consolidated log in the order the output was received.  I know this can be handled by streaming and the select, but was wanting to use the buffer since I don't have a need for real time inspection.

**Comment by daniel-nichter** [comment]
#76

**Comment by daniel-nichter** [comment]
Thank you for the contribution, @jwomackgsa. Merged, and will be in release as v1.4.2.
