### ISSUE TITLE
Windows10

### ISSUE THREAD

**Issue by Human19788** [go-cmd/cmd#77]

**Comment by Human19788** [comment]
REG ADD /?C:

**Comment by Human19788** [comment]
Human.hoseini11@outlook.com

**Comment by Human19788** [comment]
type Status struct {
    Cmd      string
    PID      int
    Complete bool
    Exit     int
    Error    error
    Runtime  float64 // seconds
    Stdout   []string
    Stderr   []string

**Comment by human1978** [comment]
Updated and install

**Comment by Human19788** [comment]
install
