### ISSUE TITLE
cant go get

### ISSUE THREAD

**Issue by jianxuanluyc** [go-cmd/cmd#91]
github.com/go-cmd/cmd@v2.0.0: invalid version: should be v0 or v1, not v2

**Comment by cheng-yang0** [comment]
commented above is the error when i go get

**Comment by cheng-yang0** [comment]
i add follow code to my go.mod, then it solve my problem.
code :
require (
   github.com/go-cmd/cmd v1
)

**Comment by daniel-nichter** [comment]
Yep, this is no v2 yet.
